/**
 * Utility to perform operations with exponential backoff retry.
 * 
 * @param {Function} operation - Async function to execute.
 * @param {Object} options - Retry options.
 * @param {number} options.maxAttempts - Maximum number of attempts.
 * @param {number} options.initialDelay - Initial delay in milliseconds.
 * @param {number} options.backoffFactor - Multiplication factor for delay.
 */
export async function withRetry(operation, { maxAttempts = 3, initialDelay = 1000, backoffFactor = 2 } = {}) {
  let lastError;
  let delay = initialDelay;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await operation();
    } catch (error) {
      lastError = error;

      // Check if error is retryable (5xx, 429, or network errors)
      // Assuming error.status is attached to standard HTTP errors if generated by axios or similar
      const status = error.status || error.response?.status;
      const isRetryable = !status || status >= 500 || status === 429;
      
      if (!isRetryable || attempt === maxAttempts) {
        throw error;
      }

      console.warn(`Attempt ${attempt} failed, retrying in ${delay}ms...`, error.message);
      await new Promise(resolve => setTimeout(resolve, delay));
      delay *= backoffFactor;
    }
  }
  throw lastError;
}
